@ECHO OFF
REM
REM open_bash.bat
REM
REM Open bash with all tools in the PATH
REM
REM Version 1.0, 10.12.2016

REM Save path to this script
SET SB_SCRIPT_PATH=%~dp0

REM Get paths and variables
CALL set_paths.bat
CALL set_vars.bat
CALL libs_versions.bat

REM Set Visual Studio environment
CALL %SB_VSTUDIO_PATH%\vcvarsall.bat %SB_VSTUDIO_ARCHITECTURE%

REM Set path
SET PATH=%PATH%;%SB_CMAKE_PATH%;%SB_NINJA_PATH%;%SB_MSYS2_PATH%;%SB_CCCL_PATH%;%SB_MINGW64_PATH%

REM Convert paths into MSYS path
SET "SB_DOWNLOAD_PATH_FWD=%SB_DOWNLOAD_PATH:\=/%"
SET "SB_DOWNLOAD_PATH_FWD2=%SB_DOWNLOAD_PATH_FWD::=%"
SET SB_DOWNLOAD_PATH_MSYS=/%SB_DOWNLOAD_PATH_FWD2%
SET "SB_INSTALL_PATH_FWD=%SB_INSTALL_PATH:\=/%"
SET "SB_INSTALL_PATH_FWD2=%SB_INSTALL_PATH_FWD::=%"
SET SB_INSTALL_PATH_MSYS=/%SB_INSTALL_PATH_FWD2%
SET "SB_SOURCE_PATH_FWD=%SB_SOURCE_PATH:\=/%"
SET "SB_SOURCE_PATH_FWD2=%SB_SOURCE_PATH_FWD::=%"
SET SB_SOURCE_PATH_MSYS=/%SB_SOURCE_PATH_FWD2%
SET "SB_CCCL_PATH_FWD=%SB_CCCL_PATH:\=/%"
SET "SB_CCCL_PATH_FWD2=%SB_CCCL_PATH_FWD::=%"
SET SB_CCCL_PATH_MSYS=/%SB_CCCL_PATH_FWD2%


REM SET CC=cccl
REM SET CXX=cccl
REM SET LD=cccl

REM SET MSYS2_PATH_TYPE=inherit

bash

pause
exit
